### ISSUE TITLE
No implementation found for void com.android.tools.aapt2.Aapt2.nativeCompile(java.util.List)

### ISSUE THREAD

**Issue by rupeshkumar22** [thejunkjon/android-tools#25]
I faced no issue in loading the shared library in MainActivity.java
So I loaded the shared libraries from private storage as follows:
```
System.load("/data/data/com.myexample.runaapt2so/files/platform/x86/system/lib/libc++.so");
System.load("/data/data/com.myexample.runaapt2so/files/platform/x86/system/lib/libprotobuf-cpp-lite.so");
System.load("/data/data/com.myexample.runaapt2so/files/x86/lib/libaapt2.so");
```
I added two extra related `x86` libraries before loading `libaapt2.so` to resolve some issues I found in the logs.
I used the java interface from [here](https://gerrit.pixelexperience.org/plugins/gitiles/frameworks_base/+/abdb26ae6a50a716a9db936dc16b4faca887646a/tools/aapt2/jni/Aapt2.java) and created an instance of the Aapt2.java from MainActivity.java as follows:

```
Aapt2 aapt2Jni = new Aapt2();
List<String> list = new ArrayList<String>();
list.add("");
aapt2Jni.compile(list);
```

I face the following issue in the logs:
```
java.lang.UnsatisfiedLinkError: No implementation found for void com.android.tools.aapt2.Aapt2.nativeCompile(java.util.List) (tried Java_com_android_tools_aapt2_Aapt2_nativeCompile and Java_com_android_tools_aapt2_Aapt2_nativeCompile__Ljava_util_List_2)
        at com.android.tools.aapt2.Aapt2.nativeCompile(Native Method)
        at com.android.tools.aapt2.Aapt2.compile(Aapt2.java:15)
        at com.myexample.runaapt2so.MainActivity.onCreate(MainActivity.java:53)
```
Attaching the full project's google drive [link](https://drive.google.com/file/d/1B7e5s4YD_0nYWBVe1RejjJmFyn-00MC3/view?usp=sharing)

Tagging @JonForShort  @TimScriptov

**Comment by JonForShort** [comment]
Hi @rupesh-kumar-lpu , have you looked at using the binary instead of the shared library? 

https://github.com/JonForShort/android-tools/tree/master/build/android-11.0.0_r33/aapt2/x86/bin

If you want to try to debug this issue, one suggestion is to dump the exported symbols using the command ```nm -gCD libaapt2.so``` and look through output to see if ```nativeCompile``` is in the list.

Hope this helps.

**Comment by rupeshkumar22** [comment]
@JonForShort Binaries are helpful and works well, But now on a higher android API level I faced permission denied error while executing binaries with runtime.execute(). Will try to export symbols as you suggested. Thanks for the information.
